### ISSUE TITLE
A standalone setting file is better.

### ISSUE THREAD

**Issue by EEOwen1996** [ladyrick/vscode-settings#1]
Copying and pasting may cause some encoding problems. So a standalone setting file is better.

**Comment by ladyrick** [comment]
Every ASCII character has the same binary bits in all the encoding modes. Or to say, ASCII characters are compatible with all the encoding modes.
So as long as I only use ASCII characters, there would be no encoding problems.

**Comment by EEOwen1996** [comment]
Thank you for your response. It makes the sense. :-)
